spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: auth-service

server:
  port: 8081

jwt:
  secret: 375c12559ffbca0f92a8b6b1a81a71ed0d6ae50a2a855825bba9479ca54db9fe
  expiration: 3600000
