server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: products
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: orders
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - name: JwtAuth
        - id: cart
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**
        - id: payments
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**
          filters:
            - name: JwtAuth

jwt:
  secret: 375c12559ffbca0f92a8b6b1a81a71ed0d6ae50a2a855825bba9479ca54db9fe
